      
mvondo_video_user_list:
    path:     /list/{page}
    defaults: { _controller: MvondoVideoBundle:VideoUser:index, page: 1 }
    requirements:
        page: \d+
        
mvondo_video_user_update:
    path:     /update/{id}
    defaults: { _controller: MvondoVideoBundle:VideoUser:update }
    requirements:
        id: \d+
    
mvondo_video_user_delete:
    path:     /delete/{id}
    defaults: { _controller: MvondoVideoBundle:VideoUser:delete }
    requirements:
        id: \d+