<?php

namespace Mvondo\VideoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    function listCategoryNbVideos() {
        return $this->getEntityManager()
                ->createQuery('SELECT c.name, c.slug, count(v.id) FROM MvondoVideoBundle:Category c JOIN c.videos v GROUP BY c.id')
                ->getResult();
    }
}
