<?php

namespace Mvondo\VideoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends EntityRepository {

    public function findAllLimitBy($limit) {
        return $this->getEntityManager()
                        ->createQuery('SELECT v FROM MvondoVideoBundle:Video v')
                        ->setMaxResults($limit)
                        ->getResult();
    }

}
