mvondo_category_list:
    path:     /admin/category/list
    defaults: { _controller: MvondoVideoBundle:Category:index }

mvondo_category_update:
    path:     /admin/category/update/{id}
    defaults: { _controller: MvondoVideoBundle:Category:update }
    requirements:
        id: \d
    
mvondo_category_delete:
    path:     /admin/category/delete/{id}
    defaults: { _controller: MvondoVideoBundle:Category:delete }
    requirements:
        id: \d
        
mvondo_video_list:
    path:     /admin/video/list
    defaults: { _controller: MvondoVideoBundle:Video:index }

mvondo_video_update:
    path:     /admin/video/update/{id}
    defaults: { _controller: MvondoVideoBundle:Video:update }
    requirements:
        id: \d
    
mvondo_video_delete:
    path:     /admin/video/delete/{id}
    defaults: { _controller: MvondoVideoBundle:Video:delete }
    requirements:
        id: \d