<?php

namespace Mvondo\CommentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * KiffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KiffRepository extends EntityRepository
{
}
