mvondo_youtube:
    resource: "@MvondoYoutubeBundle/Resources/config/routing.yml"
    prefix:   /

mvondo_site_bundle:
    resource: "@MvondoSiteBundle/Resources/config/routing.yml"

mvondo_video_bundle:
    resource: "@MvondoVideoBundle/Resources/config/routing.yml"
    
mvondo_user_bundle:
    resource: "@MvondoUserBundle/Resources/config/routing.yml"
#REST 
rest : 
  type : rest 
  resource : "routing_rest.yml"
  prefix : /api