mvondo_user:
    resource: "@MvondoUserBundle/Resources/config/routing.yml"
    prefix:   /

mvondo_video:
    resource: "@MvondoVideoBundle/Resources/config/routing.yml"
    prefix:   /

mvondo_site:
    resource: "@MvondoSiteBundle/Resources/config/routing.yml"
    prefix:   /

login: 
    pattern: /login
    defaults: {_controller: MvondoUserBundle:Security:login}

login_check:
    pattern: /login_check
    
logout: 
    pattern: logout