security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Mvondo\UserBundle\Entity\User: sha512
        
    role_hierarchy:
        ROLE_ARTIST: ROLE_USER
        ROLE_ADMIN: [ROLE_ARTIST,ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ARTIST,ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        
    providers:
        in_memory:
            memory:
                users:
                    user: { password: userpass, roles: ['ROLE_USER'] }
                    artist: { password: artistpass, roles: ['ROLE_ARTIST'] }
                    admin: { password: adminpass, roles: ['ROLE_ADMIN'] }
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                csrf_provider: security.csrf.token_manager
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path: fos_user_security_logout
                target: /     
            remember_me:
                key: %secret%
                lifetime: 360000
            
    access_control:
        - { path: ^/profile, role: ROLE_USER }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }