fos_user_security_login:
    path:     /login
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    path:     /profile/login_check
    defaults: { _controller: FOSUserBundle:Security:check }
    
fos_user_security_logout:
    path:     /profile/logout
    defaults: { _controller: FOSUserBundle:Security:logout }
